### ISSUE TITLE
Change uid and gid to different numbers

### ISSUE THREAD

**Issue by gillfimj** [sig-docker/tomcat#26]
For containers that mount volumes that need to have read/write permissions for persistent data, the tomcat user will need to have permissions on the external device. To do this, the permissions will need to be set with the uid:gid from the tomcat user of the container. However, the uid:gid might be in conflict with values that already exist on the host.  

Currently, we set the uid of 10000 as the "donotuse" user via our ansible scripts: 

from: ansible/roles/common/tasks/main.yml
```yaml
- name: Create high-number group
  group:
    name: donotuse
    gid: 10000
  tags: osuser

- name: Create high-number user
  user:
    name: donotuse
    uid: 10000
    group: donotuse
    create_home: no
    shell: /bin/false
  tags: osuser
```

However, we're setting this same uid as the tomcat uid:

```dockerfile
RUN groupadd -r -g 10001 tomcat \
 && useradd -rm -g tomcat -s /bin/bash -u 10000 tomcat \
```

Perhaps we should pick a different value well outside of any possible number scheme to avoid any conflicts with local users. Could we just add another 0 to the number, like this:

```dockerfile
RUN groupadd -r -g 100001 tomcat \
 && useradd -rm -g tomcat -s /bin/bash -u 100000 tomcat \
```
